### Get All Tasks
GET http://localhost:3000/tasks

### Get Tasks with Search
GET http://localhost:3000/tasks?status=OPEN&search=HOGE

### Create Task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "hogehoge5",
  "description": "fugafuga"
}

### Get Task By ID
GET http://localhost:3000/tasks/31663cb4-01f5-4d60-9b19-7197fb73af9f

### Delete a Task by ID
DELETE http://localhost:3000/tasks/e9ecc304-cf2a-4268-82bc-baad41866a4f

### Update a Task status by ID
PATCH  http://localhost:3000/tasks/a4085809-c1c7-4cc5-85f1-6d6e5d172ac0/status
Content-Type: application/json

{
  "status": "DONE"
}